# Generated by Django 4.1 on 2023-05-17 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trial", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee_details",
            name="id",
        ),
        migrations.AlterField(
            model_name="employee_details",
            name="Emp_id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
